-- ======================================================
-- NexusGuard APM & AI Security Sentinel - Database Schema
-- Compatible with PostgreSQL (Neon.tech / Supabase / Local)
-- ======================================================

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Services Table (Monitored Microservices)
CREATE TABLE IF NOT EXISTS services (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL UNIQUE,
    api_key VARCHAR(255) NOT NULL UNIQUE,
    environment VARCHAR(50) DEFAULT 'production',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Performance Metrics Table
CREATE TABLE IF NOT EXISTS metrics (
    id BIGSERIAL PRIMARY KEY,
    service_id UUID REFERENCES services(id) ON DELETE CASCADE,
    endpoint VARCHAR(255) NOT NULL,
    method VARCHAR(10) NOT NULL,
    status_code INT NOT NULL,
    response_time_ms FLOAT NOT NULL,
    cpu_usage_pct FLOAT NOT NULL,
    memory_usage_mb FLOAT NOT NULL,
    client_ip VARCHAR(45),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Time-series optimized index for high-speed metrics queries
CREATE INDEX IF NOT EXISTS idx_metrics_service_timestamp 
ON metrics (service_id, timestamp DESC);

-- 3. Security Threats & AI Diagnostics Table
CREATE TABLE IF NOT EXISTS security_alerts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    service_id UUID REFERENCES services(id) ON DELETE CASCADE,
    threat_type VARCHAR(100) NOT NULL, -- e.g., 'SQL Injection', 'XSS Attempt', 'DDoS Spike', 'RPS Anomaly'
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    endpoint VARCHAR(255),
    payload_sample TEXT,
    ai_diagnosis TEXT,             -- Explanation generated by Gemini AI
    recommended_patch TEXT,        -- Suggested code fix/patch generated by Gemini AI
    status VARCHAR(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'INVESTIGATING', 'RESOLVED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alerts_created_at 
ON security_alerts (created_at DESC);

-- 4. Initial Seed Data
INSERT INTO services (name, api_key, environment)
VALUES 
    ('auth-service', 'ng_live_auth_991823', 'production'),
    ('payment-gateway', 'ng_live_pay_448291', 'production'),
    ('user-api', 'ng_live_usr_771239', 'production')
ON CONFLICT (name) DO NOTHING;
